{{- if not .Values.storage.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logless-agent.fullname" . }}-auth
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "logless-agent.name" . }}
type: Opaque
data:
  {{- if .Values.storage.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.endpoint }}
  AWS_ENDPOINT_URL: {{ .Values.storage.endpoint | b64enc | quote }}
  {{- end }}
{{- end }}
